Repository meowlounge/OPSheep, pull requests merged in 2025-02, with the labels that each got.

#3 update(logic): prodbyeagle Changes
  TODO.md
  src/main/java/com/chilllounge/opsheeps/Opsheeps.java
  src/main/java/com/chilllounge/opsheeps/item/ModItems.java
  src/main/java/com/chilllounge/opsheeps/item/custom/LootManager.java
  src/main/java/com/chilllounge/opsheeps/item/custom/SuperDyeItem.java
  src/main/java/com/chilllounge/opsheeps/item/custom/SuperShearItem.java
  src/main/resources/assets/opsheeps/lang/de_de.json
  src/main/resources/assets/opsheeps/lang/en_us.json
Labels: enhancement

#5 chore(update): prodbyeagle changes
  TODO.md
  src/main/generated/.cache/baa37bca2ff0b932d6479391d5a9538baaef3975
  src/main/generated/data/opsheeps/enchantment/mineral_extractor.json
  src/main/java/com/chilllounge/opsheeps/Opsheeps.java
  src/main/java/com/chilllounge/opsheeps/OpsheepsDataGenerator.java
  src/main/java/com/chilllounge/opsheeps/datagen/EnchantmentGenerator.java
  src/main/java/com/chilllounge/opsheeps/enchantment/ModEnchantmentEffects.java
  src/main/java/com/chilllounge/opsheeps/enchantment/effect/MineralExtractorEnchantmentEffect.java
  src/main/java/com/chilllounge/opsheeps/entity/SheepEntityData.java
  src/main/java/com/chilllounge/opsheeps/item/custom/SuperDyeItem.java
  src/main/java/com/chilllounge/opsheeps/item/custom/SuperShearItem.java
  src/main/java/com/chilllounge/opsheeps/mixin/SheepEntityMixin.java
  src/main/java/com/chilllounge/opsheeps/util/OpSheepAccessor.java
  src/main/resources/assets/opsheeps/icon.png
  src/main/resources/assets/opsheeps/lang/de_de.json
  src/main/resources/assets/opsheeps/lang/en_us.json
  src/main/resources/fabric.mod.json
  src/main/resources/opsheeps.mixins.json
Labels: enhancement

#6 chore(cleanup): prodbyeagle Changes
  src/main/java/com/chilllounge/opsheeps/Opsheeps.java
  src/main/java/com/chilllounge/opsheeps/command/HelpCommand.java
  src/main/java/com/chilllounge/opsheeps/datagen/EnchantmentGenerator.java
  src/main/java/com/chilllounge/opsheeps/enchantment/ModEnchantmentEffects.java
  src/main/java/com/chilllounge/opsheeps/enchantment/effect/MineralExtractorEnchantmentEffect.java
  src/main/java/com/chilllounge/opsheeps/item/ModItemGroups.java
  src/main/java/com/chilllounge/opsheeps/item/ModItems.java
  src/main/java/com/chilllounge/opsheeps/item/custom/SuperShearItem.java
  src/main/java/com/chilllounge/opsheeps/mixin/SheepEntityMixin.java
  src/main/resources/assets/opsheeps/items/super_shear_v1.json
  src/main/resources/assets/opsheeps/items/super_shear_v2.json
  src/main/resources/assets/opsheeps/items/super_shear_v3.json
  src/main/resources/assets/opsheeps/items/super_shear_v4.json
  src/main/resources/assets/opsheeps/lang/de_de.json
  src/main/resources/assets/opsheeps/lang/en_us.json
  src/main/resources/assets/opsheeps/textures/item/gray_dye.png
  src/main/resources/assets/opsheeps/textures/item/shears_v1.png
  src/main/resources/assets/opsheeps/textures/item/shears_v2.png
  src/main/resources/assets/opsheeps/textures/item/shears_v3.png
  src/main/resources/assets/opsheeps/textures/item/shears_v4.png
Labels: enhancement

#12 add: added GrowBack Item
  src/main/java/com/chilllounge/opsheeps/item/ModItemGroups.java
  src/main/java/com/chilllounge/opsheeps/item/ModItems.java
  src/main/java/com/chilllounge/opsheeps/item/custom/GrowBackItem.java
  src/main/resources/assets/opsheeps/items/grow_back.json
  src/main/resources/assets/opsheeps/lang/de_de.json
  src/main/resources/assets/opsheeps/lang/en_us.json
  src/main/resources/assets/opsheeps/models/item/grow_back.json
  src/main/resources/assets/opsheeps/textures/item/kelp.png
Labels: enhancement

#13 fix(sheep): rainbow animation freeze
  src/main/java/com/chilllounge/opsheeps/item/custom/SuperDyeItem.java
  src/main/java/com/chilllounge/opsheeps/mixin/SheepTickMixin.java
  src/main/resources/opsheeps.mixins.json
Labels: bug

#14 fix(shears): super shears didnt break
  src/main/java/com/chilllounge/opsheeps/item/ModItems.java
  src/main/java/com/chilllounge/opsheeps/item/custom/GrowBackItem.java
  src/main/java/com/chilllounge/opsheeps/item/custom/SuperShearItem.java
Labels: bug

#16 update(LootTable, GrowBackItem): Trying new LootTable, Updated GrowBack
  src/main/java/com/chilllounge/opsheeps/item/ModItems.java
  src/main/java/com/chilllounge/opsheeps/item/custom/GrowBackItem.java
  src/main/java/com/chilllounge/opsheeps/item/custom/LootManager.java
  src/main/java/com/chilllounge/opsheeps/item/custom/SuperShearItem.java
  src/main/resources/assets/opsheeps/lang/de_de.json
  src/main/resources/assets/opsheeps/lang/en_us.json
Labels: bug, enhancement

#17 fix(SuperDyeItem): Could be used on OPSheeps
  src/main/java/com/chilllounge/opsheeps/item/custom/SuperDyeItem.java
Labels: bug

#22 fix(Enchantment): Mineral Extractor
  src/main/java/com/chilllounge/opsheeps/Opsheeps.java
  src/main/java/com/chilllounge/opsheeps/datagen/EnchantmentGenerator.java
  src/main/java/com/chilllounge/opsheeps/enchantment/ModEnchantmentEffects.java
  src/main/java/com/chilllounge/opsheeps/enchantment/effect/MineralExtractorBlockHandler.java
  src/main/java/com/chilllounge/opsheeps/enchantment/effect/MineralExtractorEffects.java
  src/main/java/com/chilllounge/opsheeps/enchantment/effect/MineralExtractorEnchantmentEffect.java
  src/main/resources/data/opsheeps/recipe/super_shear_v5.json
Labels: bug

#27 chore(Formatting): Formatted whole Codebase
  src/main/java/com/chilllounge/opsheeps/OpsheepsClient.java
  src/main/java/com/chilllounge/opsheeps/OpsheepsDataGenerator.java
  src/main/java/com/chilllounge/opsheeps/command/HelpCommand.java
  src/main/java/com/chilllounge/opsheeps/datagen/ItemModelGen.java
  src/main/java/com/chilllounge/opsheeps/datagen/RecipeGen.java
  src/main/java/com/chilllounge/opsheeps/datagen/ShearsTagGen.java
  src/main/java/com/chilllounge/opsheeps/enchantment/effect/MineralExtractorBlockHandler.java
  src/main/java/com/chilllounge/opsheeps/enchantment/effect/MineralExtractorEffects.java
  src/main/java/com/chilllounge/opsheeps/item/ModItemGroups.java
  src/main/java/com/chilllounge/opsheeps/item/ModItems.java
  src/main/java/com/chilllounge/opsheeps/item/custom/LootManager.java
  src/main/java/com/chilllounge/opsheeps/item/custom/SuperDyeItem.java
  src/main/java/com/chilllounge/opsheeps/item/custom/SuperShearItem.java
  src/main/java/com/chilllounge/opsheeps/mixin/SheepEntityMixin.java
  src/main/java/com/chilllounge/opsheeps/mixin/SheepTickMixin.java
  src/main/java/com/chilllounge/opsheeps/util/OpSheepAccessor.java
  src/main/resources/assets/opsheeps/lang/de_de.json
  src/main/resources/assets/opsheeps/lang/en_us.json
  src/main/resources/fabric.mod.json
  src/main/resources/opsheeps.mixins.json
Labels: formatting

#29 fix(Datagen): Armor now Generates Models
  src/main/generated/.cache/f3335e4a4ed3eb0c78093f18dc198b65b70851b4
  src/main/generated/assets/opsheeps/items/op_boots.json
  src/main/generated/assets/opsheeps/items/op_chestplate.json
  src/main/generated/assets/opsheeps/items/op_helmet.json
  src/main/generated/assets/opsheeps/items/op_leggings.json
  src/main/generated/assets/opsheeps/models/item/op_boots.json
  src/main/generated/assets/opsheeps/models/item/op_boots_amethyst_trim.json
  src/main/generated/assets/opsheeps/models/item/op_boots_copper_trim.json
  src/main/generated/assets/opsheeps/models/item/op_boots_diamond_trim.json
  src/main/generated/assets/opsheeps/models/item/op_boots_emerald_trim.json
  src/main/generated/assets/opsheeps/models/item/op_boots_gold_trim.json
  src/main/generated/assets/opsheeps/models/item/op_boots_iron_trim.json
  src/main/generated/assets/opsheeps/models/item/op_boots_lapis_trim.json
  src/main/generated/assets/opsheeps/models/item/op_boots_netherite_trim.json
  src/main/generated/assets/opsheeps/models/item/op_boots_quartz_trim.json
  src/main/generated/assets/opsheeps/models/item/op_boots_redstone_trim.json
  src/main/generated/assets/opsheeps/models/item/op_boots_resin_trim.json
  src/main/generated/assets/opsheeps/models/item/op_chestplate.json
  src/main/generated/assets/opsheeps/models/item/op_chestplate_amethyst_trim.json
  src/main/generated/assets/opsheeps/models/item/op_chestplate_copper_trim.json
  src/main/generated/assets/opsheeps/models/item/op_chestplate_diamond_trim.json
  src/main/generated/assets/opsheeps/models/item/op_chestplate_emerald_trim.json
  src/main/generated/assets/opsheeps/models/item/op_chestplate_gold_trim.json
  src/main/generated/assets/opsheeps/models/item/op_chestplate_iron_trim.json
  src/main/generated/assets/opsheeps/models/item/op_chestplate_lapis_trim.json
  src/main/generated/assets/opsheeps/models/item/op_chestplate_netherite_trim.json
  src/main/generated/assets/opsheeps/models/item/op_chestplate_quartz_trim.json
  src/main/generated/assets/opsheeps/models/item/op_chestplate_redstone_trim.json
  src/main/generated/assets/opsheeps/models/item/op_chestplate_resin_trim.json
  src/main/generated/assets/opsheeps/models/item/op_helmet.json
  src/main/generated/assets/opsheeps/models/item/op_helmet_amethyst_trim.json
  src/main/generated/assets/opsheeps/models/item/op_helmet_copper_trim.json
  src/main/generated/assets/opsheeps/models/item/op_helmet_diamond_trim.json
  src/main/generated/assets/opsheeps/models/item/op_helmet_emerald_trim.json
  src/main/generated/assets/opsheeps/models/item/op_helmet_gold_trim.json
  src/main/generated/assets/opsheeps/models/item/op_helmet_iron_trim.json
  src/main/generated/assets/opsheeps/models/item/op_helmet_lapis_trim.json
  src/main/generated/assets/opsheeps/models/item/op_helmet_netherite_trim.json
  src/main/generated/assets/opsheeps/models/item/op_helmet_quartz_trim.json
  src/main/generated/assets/opsheeps/models/item/op_helmet_redstone_trim.json
  src/main/generated/assets/opsheeps/models/item/op_helmet_resin_trim.json
  src/main/generated/assets/opsheeps/models/item/op_leggings.json
  src/main/generated/assets/opsheeps/models/item/op_leggings_amethyst_trim.json
  src/main/generated/assets/opsheeps/models/item/op_leggings_copper_trim.json
  src/main/generated/assets/opsheeps/models/item/op_leggings_diamond_trim.json
  src/main/generated/assets/opsheeps/models/item/op_leggings_emerald_trim.json
  src/main/generated/assets/opsheeps/models/item/op_leggings_gold_trim.json
  src/main/generated/assets/opsheeps/models/item/op_leggings_iron_trim.json
  src/main/generated/assets/opsheeps/models/item/op_leggings_lapis_trim.json
  src/main/generated/assets/opsheeps/models/item/op_leggings_netherite_trim.json
  src/main/generated/assets/opsheeps/models/item/op_leggings_quartz_trim.json
  src/main/generated/assets/opsheeps/models/item/op_leggings_redstone_trim.json
  src/main/generated/assets/opsheeps/models/item/op_leggings_resin_trim.json
  src/main/java/com/chilllounge/opsheeps/datagen/ItemModelGen.java
Labels: bug, enhancement

#31 fix(HelpCommand): Is now an Book with some content.
  gradle.properties
  src/main/generated/.cache/0a5477f6c08c7d0164e94e360e5708561e9eb5d2
  src/main/generated/.cache/e12c639bdfbb6c27a55da432860b57a10b1618db
  src/main/generated/assets/opsheeps/lang/de_de.json
  src/main/generated/assets/opsheeps/lang/en_us.json
  src/main/java/com/chilllounge/opsheeps/Opsheeps.java
  src/main/java/com/chilllounge/opsheeps/OpsheepsDataGenerator.java
  src/main/java/com/chilllounge/opsheeps/command/HelpCommand.java
  src/main/java/com/chilllounge/opsheeps/datagen/EnchantmentGen.java
  src/main/java/com/chilllounge/opsheeps/datagen/ItemModelGen.java
  src/main/java/com/chilllounge/opsheeps/datagen/lang/DeTranslationGen.java
  src/main/java/com/chilllounge/opsheeps/datagen/lang/EnTranslationGen.java
  src/main/java/com/chilllounge/opsheeps/enchantment/effect/MineralExtractorHandler.java
  src/main/java/com/chilllounge/opsheeps/item/ModItemGroups.java
  src/main/java/com/chilllounge/opsheeps/item/custom/GrowBackItem.java
  src/main/java/com/chilllounge/opsheeps/item/custom/LootManager.java
Labels: enhancement, formatting

#33 chore(OPSheeps): renamed some files
  src/main/java/com/chilllounge/opsheeps/Opsheeps.java
  src/main/java/com/chilllounge/opsheeps/command/HelpCommand.java
  src/main/java/com/chilllounge/opsheeps/datagen/EnchantmentGen.java
  src/main/java/com/chilllounge/opsheeps/datagen/ItemModelGen.java
  src/main/java/com/chilllounge/opsheeps/datagen/RecipeGen.java
  src/main/java/com/chilllounge/opsheeps/datagen/ShearsTagGen.java
  src/main/java/com/chilllounge/opsheeps/enchantment/OpSheepsEnchantmentEffects.java
  src/main/java/com/chilllounge/opsheeps/enchantment/effect/MineralExtractorHandler.java
  src/main/java/com/chilllounge/opsheeps/item/OpSheepsItemGroups.java
  src/main/java/com/chilllounge/opsheeps/item/OpSheepsItems.java
  src/main/java/com/chilllounge/opsheeps/util/ShearTags.java
Labels: enhancement

#34 feat(SuperShear): added perks
  src/main/generated/.cache/0a5477f6c08c7d0164e94e360e5708561e9eb5d2
  src/main/generated/.cache/e12c639bdfbb6c27a55da432860b57a10b1618db
  src/main/generated/assets/opsheeps/lang/de_de.json
  src/main/generated/assets/opsheeps/lang/en_us.json
  src/main/java/com/chilllounge/opsheeps/datagen/lang/DeTranslationGen.java
  src/main/java/com/chilllounge/opsheeps/datagen/lang/EnTranslationGen.java
  src/main/java/com/chilllounge/opsheeps/item/custom/SuperShearItem.java
Labels: feature

#35 fix(OpSetLoot): tiny change
  src/main/java/com/chilllounge/opsheeps/enchantment/effect/MineralExtractorEffects.java
  src/main/java/com/chilllounge/opsheeps/item/OpArmorMaterial.java
  src/main/java/com/chilllounge/opsheeps/item/OpSetLoot.java
Labels: bug, enhancement

#38 update(OpArmorMaterial): changes values
  src/main/java/com/chilllounge/opsheeps/item/OpArmorMaterial.java
Labels: enhancement

#39 feat(Components): Added Components but doesn't work
  src/main/java/com/chilllounge/opsheeps/Opsheeps.java
  src/main/java/com/chilllounge/opsheeps/OpsheepsDataGenerator.java
  src/main/java/com/chilllounge/opsheeps/datagen/EnchantmentGen.java
  src/main/java/com/chilllounge/opsheeps/datagen/ModItemsTagGen.java
  src/main/java/com/chilllounge/opsheeps/datagen/ShearsTagGen.java
  src/main/java/com/chilllounge/opsheeps/enchantment/OpSheepsEnchantmentEffects.java
  src/main/java/com/chilllounge/opsheeps/item/OpSetLoot.java
  src/main/java/com/chilllounge/opsheeps/util/ModItemTags.java
  src/main/java/com/chilllounge/opsheeps/util/ShearTags.java
Labels: bug, help wanted

#40 fix(Enchantments): fixed CRASHOUT / DUMBASS code by @DWHIncAndi
  src/main/generated/.cache/cab39eee0b7c76dcff8e5682c39189d52ae61431
  src/main/generated/.cache/ff1b1ad58828e989a24343f7bac5c08d0c49881e
  src/main/generated/data/minecraft/tags/item/enchantable/armor.json
  src/main/generated/data/minecraft/tags/item/enchantable/mining.json
  src/main/generated/data/minecraft/tags/item/enchantable/mining_loot.json
  src/main/generated/data/minecraft/tags/item/enchantable/sharp_weapon.json
  src/main/java/com/chilllounge/opsheeps/datagen/ModItemsTagGen.java
  src/main/java/com/chilllounge/opsheeps/item/OpSetLoot.java
  src/main/java/com/chilllounge/opsheeps/item/custom/LootManager.java
Labels: bug, enhancement

#41 feature(OPSheeps): v1.0.0
  gradle.properties
  src/main/java/com/chilllounge/opsheeps/item/OpSheepsItemGroups.java
  src/main/java/com/chilllounge/opsheeps/item/OpSheepsItems.java
  src/main/java/com/chilllounge/opsheeps/item/custom/LootManager.java
Labels: enhancement, feature
